input {
  # Logstash écoute les logs JSON envoyés via un socket TCP sur le port 5000
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  # On s'assure que chaque événement a un horodatage
  mutate {
    add_field => { "app_name" => "orion-crm" }
  }
}

output {
  # Envoie des logs vers Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orion-logs-%{+YYYY.MM.dd}"
  }
  # Affiche les logs dans la console Docker de Logstash pour faciliter le débogage
  stdout {
    codec => rubydebug
  }
}
