# Clé unique et nom du projet dans SonarQube Cloud
sonar.projectKey=yaokissi
sonar.organization=yaokissi
sonar.projectName=Orion CRM Application


# Version du projet
sonar.projectVersion=1.0.0

# Répertoires sources à analyser (Front-end et Back-end)
sonar.sources=client/src,server/src

# Inclusion des fichiers de tests
sonar.tests=client/src,server/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclusions d'analyse (fichiers générés, dépendances, builds)
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,**/*.config.js,**/vite-env.d.ts

# Emplacement des rapports de couverture de code (format LCOV généré par Vitest)
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info

# Encodage du code source
sonar.sourceEncoding=UTF-8
